const recipeSeed = [{
        title: "Strawberry Chia delighttttttt",
        intro: "Strawberry desserts are among my favorite list of desserts, and the amazing thing is that there are so many recipes and ways of using your strawberry, and it can never get boring.",
        preparation_time: 40,
        cook_time: 20,
        image: "https://cdn.pixabay.com/photo/2017/03/31/18/02/strawberry-dessert-2191973__480.jpg",
        ingredients: ["2 cups (284g) all-purpose flour", "plus more for dusting pan",
            "3 Tbsp (26g) cornstarch",
            " 1/2 tsp salt",
            " 1/2 tsp baking soda",
            "1/2 tsp baking powder",
            "12 Tbsp (170g) unsalted butter, softened",
            "1 1/2 cups (315g) granulated sugar",
            "1 tsp lemon zest",
            " 4 large eggs",
            " 1 1/2 tsp vanilla extract",
            "1 cup (283g) sour cream",
            "2 lbs fresh strawberries, diced, plus 12 more small whole for garnish",
            "3 1/2 Tbsp (45g) granulated sugar"

        ],
        directions: ["Preheat oven to 350 degrees F. Butter and flour an 18-by-13-inch rimmed baking sheet. In a mixing bowl whisk together flour, cornstarch, salt, baking soda and baking powder, set aside",
            "In the bowl of an electric stand mixer fitted with the paddle attachment whip together butter, sugar and lemon zest until pale and fluffy. Mix in eggs one at a time then mix in vanilla",
            "Add 1/3 of the flour mixture and mix just until combined then add in 1/2 the sour cream and mix just until combined, repeat with flour and sour cream once more then end by mixing in last 1/3 of the flour mixture and mixing just until combined (scrape down bowl to ensure it's evenly combined)",
            "Pour and spread batter evenly into prepared baking sheet. Bake in preheated oven until toothpick inserted into center comes out clean, about 20 - 24 minutes",
            "Remove from oven and cool completely on a wire rack. Once cool cut into 24 rounds the size of your dessert cups (you'll have a little left over cake which you can chill or freeze and serve later with more fresh fruit and whipped cream)"
        ],

    },
    {
        title: "Death by Chocolate",
        intro: "A nod to the classic childhood favorite, this chocolate cake roll combines light chocolate sponge cake with sweet vanilla whipped cream and chocolate ganache. Rich and totally irresistible, this dessert is for chocolate lovers everywhere",
        preparation_time: 30,
        cook_time: 10,
        image: "https://cdn.pixabay.com/photo/2017/12/14/19/47/cake-3019645_1280.jpg",
        ingredients: ["FOR THE CHOCOLATE CAKE",
            "Butter, For Greasing",
            "1/4 c. Unsweetened Cocoa Powder, Plus More For Sprinkling",
            "1/3 c. All-purpose Flour",
            " 1/4 tsp. Salt",
            "4 Large Eggs",
            "1/2 c. Granulated Sugar",
            "4 tbsp. Unsalted Butter, melted",
            "FOR THE CREAM FILLING:",
            "1 c. Heavy Cream",
            "1/4 c. Sugar",
            "1 tsp. Vanilla Extract",
            "FOR THE CHOCOLATE GANACHE:",
            "4 oz. weight Bittersweet Chocolate Chips Or Chopped Chocolate",
            " 1/2 c. Heavy Cream",
            "1 tbsp. Milk",
        ],
        directions: ["To make the chocolate cake, preheat the oven to 425ºF", "Place a piece of parchment paper or a silicone mat on a 17x12 sheet pan, and rub butter on it to grease",

            "In a large bowl, whisk to combine the cocoa powder, flour, and salt",

            "Bring an inch of water to a simmer in a medium saucepan. Combine the eggs and sugar in a heatproof glass bowl, then place over the simmering water (make sure the water doesn’t touch the bowl). Using a hand mixer, beat the eggs and sugar together over medium speed for about two minutes, until the eggs are thick, pale yellow, and warm to the touch (if you have a thermometer, you want the eggs to be about 120ºF. If you don’t have a thermometer, just touch the mixture with your finger every once in a while until it feels like hot tap water)",

            "Remove the egg bowl from the heat and continue beating at medium high speed for another 3 minutes, until it’s thick and airy, and has reached the ribbon stage. That means when you drag and drizzle a spoonful of the liquid, it shouldn’t settle back into the liquid for a good 5–10 seconds. Mix in the melted butter",

            "Add the dry ingredients to the mixture, and gently fold it into the eggs with a spatula, working quickly. Spread the batter onto the buttered parchment or silicone mat, leaving an inch from the edges. Bake the cake for 5–6 minutes, until springy to the touch",

            "Place a piece of parchment paper on a flat surface and sprinkle lightly with cocoa powder. Flip the cake onto the parchment, then remove the parchment or silicone mat that the cake baked on. Gently roll the cake up into a log while it’s still warm. This is like muscle memory for the cake, and it will roll easier again later",

            "To make the filling, combine the heavy cream, sugar, and vanilla extract in a large bowl, and whip with a hand mixer to stiff peaks, about 5 minutes on medium speed",

            "Unroll the cooled cake, then spread the cream all over, leave a 1-inch border around all edges. Roll the cake up gently (leaving the parchment paper behind), then place on a wire rack",

            "To make the chocolate ganache, microwave the cream and chocolate in a heatproof bowl in 30-second intervals, stirring after each time, until combined. Add the tablespoon of milk, which will give a more pourable consistency. Pour the chocolate ganache evenly over the cake, then refrigerate for 20 minutes before serving, so the ganache can firm up",

            "The cake is now ready to be sliced and served. Enjoy!",
        ],


    },
    {
        title: "Swedish Crepes",
        intro: "These homemade crepes are ultra thin and delicate with the most buttery crisp edges. Easy to make with just a blender and regular skillet, they’re ready for your choice of sweet or savory fillings and toppings. No special pans required for these French-style pancakes. And, best part of all, you only need 8 basic ingredients",
        preparation_time: 30,
        cook_time: 60,
        image: "https://cdn.pixabay.com/photo/2019/01/10/20/31/pancakes-3926009__480.jpg",
        ingredients: ["3 Tablespoons (43g) unsalted butter, plus 3-4 more Tablespoons for the pan",
            "1 cup (125g) all-purpose flour (spoon & leveled)",
            "1 Tablespoon granulated sugar",
            "1/8 teaspoon salt",
            "3/4 cup (180ml) whole milk, at room temperature",
            "1/2 cup (120ml) room temperature water",
            "2 large eggs, at room temperature",
            "1 and 1/2 teaspoons pure vanilla extract",
        ],
        directions: ["Melt 3 Tablespoons of butter in the microwave or on the stove", "Cool for about 5 minutes before using in the next step. The remaining butter is for the skillet",
            "Combine the cooled melted butter, flour, sugar, salt, milk, water, eggs, and vanilla to a blender or large food processor.  If you don’t have a blender or food processor, use a large mixing bowl and whisk by hand. Blend on medium-high speed for 20-30 seconds until everything is combined", "The mixture will be silky smooth and the consistency of cream. Cover the blender tightly or pour into a medium bowl, cover tightly, and chill in the refrigerator for 30-60 minutes and up to 1 day. (After refrigerating, if the batter looks separated, give it a quick stir before cooking in the next step.)",
            "Cook the crepes: Use the remaining butter for greasing the pan between each crepe. Place an 8-inch skillet over medium heat and generously grease it with some of the reserved butter. If you don’t have a skillet this size, use a larger one but make sure you keep the crepes thin. Once the skillet is hot, pour 3-4 Tablespoons (closer to 3 is best) of batter into the center of the pan. Tilt/twirl the pan so the batter stretches as far as it will go. The thinner the crepe, the better the texture. Cook for 1-2 minutes, then flip as soon as the bottom is set",
            "Don’t wait too long to flip crepes or else they will taste rubbery. Cook the other side for 30 seconds until set. Transfer the cooked crepe to a large plate and repeat with the remaining batter, making sure to butter the pan between each crepe",
            "If desired, separate each crepe with parchment paper so they do not stick together. Though, if using enough butter in your pan, the crepes won’t stick",
            "Fill the crepes. I love serving them warm, but they’re excellent at room temperature too. See my filling suggestions above this recipe or my recipe notes below. Place a few spoonfuls of your filling ingredient(s) in the center of the crepe. Fold both sides over the filling. Crepes are delicious with toppings, too, such as a drizzle of melted chocolate, melted peanut butter, or a dusting of confectioners’ sugar. Or a savory sauce like pesto or hollandaise",
            "Leftover unfilled crepes remain fresh in an airtight container in the refrigerator for 1 day or in the freezer for 1 month. Freeze each between small sheets of parchment paper so they don’t stick. (I usually layer them with parchment and freeze in a large zipped-top bag.) Thaw at room temperature before filling/enjoying. See reheating instructions in my Make Ahead Instructions recipe note below",
        ],


    },
    {
        title: "Berry cheesecake",
        intro: "Blueberries, blackberries, raspberries, and strawberries make this no-bake cheesecake a springtime favourite",
        preparation_time: 15,
        cook_time: 120,
        image: "https://cdn.pixabay.com/photo/2018/07/22/18/26/cake-3555186__480.jpg",
        ingredients: ["Berry Puree:",
            "4 oz raspberries",
            " 6 oz strawberries",
            "6 oz blueberries",
            "2/3 cup white granulated sugar",
            "1 tsp lemon juice",
            "Crust:",
            "1 ½ cups graham cracker crumbs",
            "½ cup brown sugar",
            "1 tsp vanilla extract",
            "5 Tbsp melted unsalted butter",
            "1/3 cup of berry puree",
            "Cheesecake:",
            "4 8 oz packs of cream cheese softened",
            "½ cup sour cream",
            "2 eggs",
            "¾ cup heavy cream",
            "¾ cup white granulated sugar",
            "2 Tbsp corn starch",
            "2 tsp vanilla extract",
            " Topping:",
            "4 oz fresh raspberries",
            "6 oz fresh strawberries",
            "6 oz fresh blueberries",
            "About 1/2 cup of berry puree add more on top if you wish or save some for individual servings",
        ],
        directions: ["Berry Puree:",
            "In a sauce pot, over medium heat, combine all berries, sugar, and lemon juice. Stir and let it cook, uncovered. Make sure to stir every few minutes. Let the berries simmer for about 20 minutes, some of the liquid will cook down",
            "Take the sauce pot off heat and puree the mixture either with an immersion blender or in a separate blender. Set aside",
            "Preheat the oven to 325 and grease a 9 inch spring form. You will need a large roasting pan (one that’s bigger and longer than the spring form. I use the aluminum foil disposable roasting pan.)",
            "Crust:",
            "In a small bowl, combine graham cracker crumbs, melted butter, vanilla extract and brown sugar. Mix very well",
            "Spread crumb mixture in the bottom on the spring form, evenly, pressing it over the bottom and about half way up the sides",
            "Spread 1/3 cup of berry puree evenly over the crust.",
            "Cheesecake:",
            "In a bowl of an electric mixer, beat cream cheese on medium-high speed until smooth and fluffy. Scrape sides and bottom on the bowl and beat for another minute.",
            "Add corn starch and sugar and mix until combined.",
            "Beat in eggs, one at a time, until well incorporated.",
            "Add sour cream, vanilla extract, and heavy cream, and beat until all mixed very well.",
            "Drop scoops of cheesecake batter all over the crust, covering it completely and then even it out. (If you just pour in the batter, it will start mixing with berry puree.)",
            "(If you are not sure about your springform holding up in water, you can wrap the springform in heavy duty aluminum foil from bottom up to the sides, pressing it tight to the outside of the springform.)",
            "Place roasting pan into the oven and place cheesecake springform inside the roasting pan. Carefully add water to the roasting pan, about half way up the side of the spring form.",
            "Bake for 85-90 minutes. Turn off the oven and open the oven door half way. Let cheesecake rest for 10 minutes and take it out of the oven (out of the water bath).",
            "Let it rest for 10-15 minutes on the counter and then gently run a greased butter knife between sides of the cheesecakes and the springform to carefully separate it. (You don't actually have to take the cheesecake out of the pan until ready to add toppings.) Let it cool to the room temperature before covering and putting it in the fridge.",
            "Refrigerate the cheesecake for at least 6 hours or overnight. (You can transfer the berry puree into a glass jar until ready to use.)",

            "Topping:",
            "When ready to serve the cheesecake, take the side rim of the springform off. Pour 1/2 cup of berry puree on top of the cheesecake, in the center. Gently spread it with a spatula over the top. Then, add berries. It's easier to place strawberries first and then add blueberries and raspberries.",
            "If you will have leftover, just put the side rim of the springform back on and cover it with a saran wrap over the top.",
        ],


    },
    {
        title: "Swirl Apple Studel",
        intro: "Get mesmerized with this swirly cinnamon pie, filled to the brim with cinnamon sugar coated apples. A fun spin on your traditional apple pie and just as easy to make, if not easier! Serve warm with your favorite creamy vanilla ice cream.",
        preparation_time: 30,
        cook_time: 55,
        image: "https://cdn.pixabay.com/photo/2018/09/24/17/04/strudel-3700361__480.jpg",
        ingredients: ["1/2 cup light brown sugar (packed)",
            "1-1/2 teaspoons ground cinnamon",
            "2 large eggs",
            "1/2 cup granulated sugar",
            "1/2 cup (1 stick) unsalted butter, melted and slightly cooled",
            "1/2 cup milk",
            "2 teaspoons vanilla extract",
            "1-1/2 cups all-purpose flour, spooned into measuring cup and leveled-off",
            "1/2 teaspoon salt",
            "1-1/2 teaspoons baking powder",
            "1 cup peeled, cored, and finely diced tart baking apples, from 1 apple (preferably Granny Smith)",
        ],
        directions: ["Preheat the oven to 350°F and set an oven rack in the middle position. Spray an 8.5 x 4.5-inch loaf pan lightly with nonstick cooking spray. Line the long side of the pan with a parchment paper “sling” and spray lightly with nonstick cooking spray again.",
            "In a small bowl, mix the brown sugar and cinnamon until evenly combined. Set aside.",
            "In the bowl of an electric mixer fitted with the paddle attachment or beaters, beat the eggs and granulated sugar on medium speed until pale and creamy, about 2 minutes.",
            "With the mixer on low, gradually add the melted butter followed by the milk and vanilla, and mix just until evenly combined.",
            "Add the flour, salt, and baking powder to the batter and mix on low speed until evenly combined.",
            "Add the apples to the batter and fold with a rubber spatula until evenly incorporated.",
            "Spoon about 2/3 of the batter into the prepared pan. Sprinkle about 2/3 of the brown sugar-cinnamon mixture on top of the batter. Spoon the remaining batter over top, followed by the remaining brown sugar-cinnamon mixture. Using a butter knife, swirl the layers by making a zig-zag motion through the batter once in each direction (don't overdo it!).",
            "Bake for about 50 minutes, until the bread is golden brown and a cake tester or toothpick inserted into the center comes out clean. Let the bread cool on a rack for about 30 minutes, then use the parchment sling to lift the bread out of the pan and onto the rack. Let cool completely before slicing, a few hours or overnight. Store loosely covered with aluminum foil on the countertop for up to 4 days.",
        ],


    },
    {
        title: "Rasberry Delite",
        intro: "",
        preparation_time: 20,
        cook_time: 20,
        image: "https://cdn.pixabay.com/photo/2017/03/03/18/40/quark-2114690_1280.jpg",
        ingredients: ["2 cups fresh raspberries",
            "1/2 cup sugar",
            "1 tablespoon lemon juice",
            "1-1/2 teaspoons unflavored gelatin",
            "1/4 cup cold water",
            "1 cup heavy whipping cream",
        ],
        directions: ["Place the raspberries in a food processor; cover and puree. Strain and discard seeds. Transfer puree to a large bowl. Stir in sugar and lemon juice; set aside.",
            "In a small saucepan, sprinkle gelatin over cold water; let stand for 1 minute. Stir over low heat until gelatin is completely dissolved. Stir into raspberry mixture. Refrigerate until slightly thickened, about 1 hour.",
            "Transfer gelatin mixture to a large bowl. Beat on high speed until foamy. Gradually add cream; beat until thickened, about 2 minutes. Spoon into dessert dishes. Cover and refrigerate until set, 1-2 hours.",
        ],


    },
    {
        title: "Cherry Cake",
        intro: "This fast and easy Cherry Cake is deliciously moist, made with yogurt and bursting with fresh cherries. Serve it plain or with a dollop of whipped cream and a fresh chocolate dipped cherry!",
        preparation_time: 20,
        cook_time: 20,
        image: "https://cdn.pixabay.com/photo/2017/06/01/19/44/cherry-pie-2364352__480.jpg",
        ingredients: ["2 cups fresh cherries pitted (270 grams)",
            "1 1/4 cups + 2 tablespoons flour (180 grams)",
            "1 1/2 teaspoons baking powder",
            "1/4 teaspoon baking soda",
            "1 egg*",
            "1 egg yolk*",
            "1/2 cup + 2 1/2 tablespoons sugar (80 grams)",
            "zest 1/2 lemon",
            "1 teaspoon vanilla",
            "1/4 cup vegetable oil (I use corn or sunflower oil) (50 grams)",
            "1/2 cup regular yogurt* (125 grams)",
            "1/4 cup milk* (60 grams)",
            "1 tablespoon sugar",
            "*Remove from fridge 30 minutes before using.",
            "TOPPING",
            "1-2 cups whipped cream",
            "10-12 cherries (whole)",
            "2-3 ounces chocolate (melted) (50 grams)",
        ],
        directions: ["Pre-heat oven to 350F (180C), grease and flour an 8 inch cake pan (springform pan is the best if you have it).",
            "In a medium bowl whisk together flour, baking powder and baking soda.",
            "In a large bowl beat on medium speed the eggs and sugar and until light and fluffy, (approximately 2-3 minutes), then add the zest and vanilla beat for one minute, then slowly add the vegetable oil and continue beating.  Add the yogurt and milk and beat on low speed to combine,  add the flour a third at a time, beating on low and scraping the bowl after each addition just until smooth.",
            "Fold half the pitted cherries* into the batter then pour into the prepared cake pan, top with remaining cherries, press down lightly with a spatula. Sprinkle with 1 tablespoon of granulated sugar. Bake for approximately 40-45 minutes.",
            "Let cool completely before serving if desired top powdered sugar, whipped cream and  chocolate dipped cherries.  Enjoy!",
            "* Toss the cherries with a couple of teaspoons of all purpose flour and mix to coat.",
        ]

    },
    {
        title: "Blueberry Muffins",
        intro: "These muffins are extra large and yummy with the sugary-cinnamon crumb topping. I usually double the recipe and fill the muffin cups just to the top edge for a wonderful extra-generously-sized deli style muffin. Add extra blueberries too, if you want!",
        preparation_time: 15,
        cook_time: 25,
        image: "https://cdn.pixabay.com/photo/2019/02/17/16/23/muffins-4002553__480.jpg",
        ingredients: ["½ cups all-purpose flour", 
        "¾ cup white sugar",
        "½ teaspoon salt",
        "2 teaspoons baking powder",
        "⅓ cup vegetable oil ",
        "1 egg",
        "⅓ cup milk, or more as needed",
        "1 cup fresh blueberries", 
        "½ cup white sugar",
        "⅓ cup all-purpose flour",
        "¼ cup butter, cubed",
        "1 ½ teaspoons ground cinnamon",
        ],
        directions: ["Preheat oven to 400 degrees F (200 degrees C).",
        "Grease muffin cups or line with muffin liners.",
        "Combine 1 1/2 cups flour, 3/4 cup sugar, salt and baking powder. Place vegetable oil into a 1 cup measuring cup; add the egg and add enough milk to reach the 1-cup mark. Mix this with flour mixture. Fold in blueberries. Fill muffin cups right to the top, and sprinkle with crumb topping mixture.",
        "To Make Crumb Topping: Mix together 1/2 cup sugar, 1/3 cup flour, 1/4 cup butter, and 1 1/2 teaspoons cinnamon. Mix with fork, and sprinkle over muffins before baking.",
        "Bake for 20 to 25 minutes in the preheated oven, or until done.",
        ]

    },
    {
        title: "Multicolored French Macaroons",
        intro: "Instead of the straightforward sweet, coconutty chew of classic macaroons, these have a more rounded richness, and a welcome savory oomph.",
        preparation_time: 120,
        cook_time: 20,
        image: "https://cdn.pixabay.com/photo/2020/03/19/21/40/easter-4948871__480.jpg",
        ingredients: ["1 cup almond flour",
        "3 large egg whites, at room temperature",
        "1/4 teaspoon cream of tartar",
        "Pinch of salt",
        "1/4 cup superfine sugar",
        "2 to 3 drops gel food coloring (see below)",
        "1/2 teaspoon vanilla, almond or mint extract",
        ],
        directions: ["Special equipment: Oven with convection setting, 4 baking sheets, 3 silicone baking mats, Fine-mesh sieve, Pastry bag with 1/4-inch round tip",
        "Preheat the oven to 300 degrees F using the convection setting. Line 3 baking sheets with silicone mats. Measure the confectioners' sugar and almond flour by spooning them into measuring cups and leveling with a knife. Transfer to a bowl; whisk to combine.",
        "Sift the sugar-almond flour mixture, a little at a time, through a fine-mesh sieve into a large bowl, pressing with a rubber spatula to pass through as much as possible. It will take a while, and up to 2 tablespoons of coarse almond flour may be left; just toss it.",
        "Beat the egg whites, cream of tartar and salt with a mixer on medium speed until frothy. Increase the speed to medium high; gradually add the superfine sugar and beat until stiff and shiny, about 5 more minutes.",
        "Transfer the beaten egg whites to the bowl with the almond flour mixture. Draw a rubber spatula halfway through the mixture and fold until incorporated, giving the bowl a quarter turn with each fold.",
        "Add the food coloring and extract (see below). Continue folding and turning, scraping down the bowl, until the batter is smooth and falls off the spatula in a thin flat ribbon, 2 to 3 minutes.",
        "Transfer the batter to a pastry bag fitted with a 1/4-inch round tip. Holding the bag vertically and close to the baking sheet, pipe 1 1/4-inch circles (24 per sheet). Firmly tap the baking sheets twice against the counter to release any air bubbles.",
        "Let the cookies sit at room temperature until the tops are no longer sticky to the touch, 15 minutes to 1 hour, depending on the humidity. Slip another baking sheet under the first batch (a double baking sheet protects the cookies from the heat).",
        "Bake the first batch until the cookies are shiny and rise 1/8 inch to form a 'foot,' about 20 minutes. Transfer to a rack to cool completely. Repeat, using a double sheet for each batch. Peel the cookies off the mats and sandwich with a thin layer of filling"
        ]

    }
]
module.exports = recipeSeed;